### ISSUE TITLE
Cloud formation initial setup for micro-service audio converter

### ISSUE THREAD

**Issue by pietrop** [bbc/digital-paper-edit-audio-converter#1]
- [x] 1. microservice is deployed in Cosmos (int, stage at the least)
- [x]  2. microservice has an SQS, which it polls from
- [x]  3. microservice subscribes to API's topic

Note that 
>They are all cloud-formation type stuff, so it should / can be done in one session. The second point is not actually about the logic of the code which is what #3 is addressing. It only deals with setting it up in cloudformation :)

**Comment by emettely** [comment]
# Acceptance Criteria
microservice is deployed in Cosmos (int, stage at the least)
microservice has an SQS, which it polls from
microservice subscribes to API's topic

**Comment by pietrop** [comment]
PR https://github.com/bbc/digital-paper-edit-audio-converter/pull/3

**Comment by pietrop** [comment]
could these be 3 separate cards/issues? (to make them easier to review, move along etc..)
- [ ] 1.microservice is deployed in Cosmos (int, stage at the least)
- [ ] 2.microservice has an SQS, which it polls from
- [ ] 3.microservice subscribes to API's topic

Seem slike this PR https://github.com/bbc/digital-paper-edit-audio-converter/pull/3/files is addressing  the second one? 

Unless I am missing something (cc @emettely @jamesdools )

**Comment by emettely** [comment]
They are all cloud-formation type stuff, so it should can be done in one session.

**Comment by jamesdools** [comment]
Have put the resources in Cloudformation in this branch and built them for `int` on Cosmos. If this PR is just Cloudformation then it's ready for review - build & deploy can be done after.
