### ISSUE TITLE
Audio Converter successfully builds in Jenkins

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-audio-converter#6]
# Context
In order to complete https://github.com/bbc/digital-paper-edit-audio-converter/issues/1 we need to make sure that the RPM can build in https://jenkins.newslabs.tools.bbc.co.uk/job/digital-paper-edit-audio-converter/ builds

# Acceptance Criteria
- [x] package.json has dev dependency for speculate
- [x] spec config in package.json
- [ ] copy over the bake-scripts in API
in https://github.com/bbc/digital-paper-edit-audio-converter/
- [ ] https://jenkins.newslabs.tools.bbc.co.uk/job/digital-paper-edit-audio-converter/ builds

# References
Refer to set up (package.json, bakescripts below)
https://github.com/bbc/digital-paper-edit-api/

**Comment by pietrop** [comment]
successfully built on Jenkins form PR https://github.com/bbc/digital-paper-edit-audio-converter/pull/7
seems like it was only missing the bake scripts..

**Comment by pietrop** [comment]
also successfully deployed on cosmos 
https://digital-paper-edit-audio-converter.int.tools.bbc.co.uk/status
